version: "3.1"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "9mREsvXDs9Gk89Ef"
    volumes:
      - ./data/dataBase:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"